-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Nur vollständig geprüfte Einträge je Thema und Partei; alles andere gilt als „noch nicht erfasst“.
-- Ausnahme: KI-Entwürfe (ki_entwurf = true), nur mit Zugang zur geschlossenen Testphase sichtbar.

-- Mehrfach ausführbar: Stammdaten per Upsert, Maßnahmen und Abdeckung werden neu geschrieben.
-- Gespielte Runden bleiben erhalten.
delete from public.massnahmen;
delete from public.abdeckung;
delete from public.landesprogramme;

insert into public.parteien (id, name, kurzname, farbe, programm_url, programm_stand) values
  (11, 'CDU/CSU', 'Union', '#8a96a3', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf', '2024-12-17'),
  (12, 'SPD', 'SPD', '#f0605d', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf', '2025-01-11'),
  (13, 'Bündnis 90/Die Grünen', 'Grüne', '#6fbf4a', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf', '2025-01-26'),
  (14, 'FDP', 'FDP', '#ffe74d', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf', '2025-02-09'),
  (15, 'AfD', 'AfD', '#4fb8e8', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf', '2025-01-12'),
  (16, 'Die Linke', 'Linke', '#e0659b', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf', '2025-01-18'),
  (17, 'BSW', 'BSW', '#b784c9', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf', '2025-01-12')
on conflict (id) do update set name = excluded.name, kurzname = excluded.kurzname, farbe = excluded.farbe,
  programm_url = excluded.programm_url, programm_stand = excluded.programm_stand;

-- Parteien, die nicht mehr im Katalog stehen (z. B. fiktive nach dem Umstieg), entfernen.
-- Gespielte Runden bleiben erhalten, ihr Parteiverweis wird leer.
delete from public.parteien where id not in (11, 12, 13, 14, 15, 16, 17);

insert into public.laender (id, name, letzte_wahl) values
  ('BE', 'Berlin', '2026-09-20'),
  ('MV', 'Mecklenburg-Vorpommern', '2026-09-20'),
  ('ST', 'Sachsen-Anhalt', '2026-09-06')
on conflict (id) do update set name = excluded.name, letzte_wahl = excluded.letzte_wahl;
delete from public.laender where id not in ('BE', 'MV', 'ST');

insert into public.themen (id, name, beschreibung) values
  (1, 'Arzttermine', 'Lange Wartezeiten und schwer erreichbare Praxen.'),
  (2, 'Miete', 'Hohe Mieten und schwierige Wohnungssuche.'),
  (3, 'Energiepreise', 'Hohe Kosten für Strom und Heizung.'),
  (4, 'Schule', 'Unterrichtsausfall, fehlende Lehrkräfte und marode Schulgebäude.'),
  (5, 'Arbeitsplätze', 'Unsichere Jobs, Stellenabbau und schwache Wirtschaft.'),
  (6, 'Zuwanderung und Integration', 'Probleme bei Aufnahme, Integration und Rückführung von Zugewanderten.'),
  (7, 'Rente', 'Niedrige Renten und Sorge um die Altersvorsorge.'),
  (8, 'Bus und Bahn', 'Seltene Verbindungen, Ausfälle und Verspätungen.'),
  (9, 'Sicherheit', 'Sich im Alltag unsicher fühlen oder Opfer von Kriminalität werden.'),
  (10, 'Pflege', 'Pflegeplatz oder Pflegedienst finden, hohe Kosten, überlastete Angehörige.')
on conflict (id) do update set name = excluded.name, beschreibung = excluded.beschreibung;

insert into public.ursachen (id, thema_id, beschreibung, quelle_url, ebene) values
  (101, 1, 'Zu wenige Hausarztpraxen, besonders auf dem Land; viele Ärztinnen und Ärzte gehen bald in den Ruhestand', 'https://idw-online.de/de/news769524', 'bund'),
  (102, 1, 'Termine und Wege durch das Gesundheitssystem werden kaum gesteuert; knappes Personal wird nicht gezielt eingesetzt', 'https://www.svr-gesundheit.de/publikationen/gutachten-2024/', 'bund'),
  (103, 1, 'Unterschiedliche Vergütung: Facharztpraxen vergeben Termine bevorzugt an Privatversicherte', 'https://idw-online.de/de/news750098', 'bund'),
  (201, 2, 'Es werden weniger Wohnungen gebaut als gebraucht (Bedarf laut Prognose rund 320.000 pro Jahr)', 'https://www.bbsr.bund.de/BBSR/DE/presse/presseinformationen/2025/wohnungsbedarfsprognose.html', 'bund'),
  (202, 2, 'Mieten bei Neuvermietung liegen rund 43 % über Bestandsmieten, in großen Städten besonders hoch', 'https://www.bbsr.bund.de/BBSR/DE/startseite/topmeldungen/entwicklung-wohnungsmieten-2025.html', 'bund'),
  (203, 2, 'Stark gestiegene Baukosten: Wohngebäude wurden 2010 bis 2025 um 89 % teurer, mehr als doppelt so stark wie die Inflation', 'https://www.destatis.de/DE/Themen/Wirtschaft/Preise/Baupreise-Immobilienpreisindex/_inhalt.html', 'bund'),
  (204, 2, 'Mieten in laufenden Verträgen steigen weiter (Nettokaltmieten 2025 im Schnitt +2,1 %)', 'https://www.destatis.de/DE/Presse/Pressemitteilungen/2026/01/PD26_019_611.html', 'bund'),
  (301, 3, 'Hohe Netzentgelte für den Betrieb und Ausbau der Stromnetze', 'https://www.bundesnetzagentur.de/DE/Vportal/Energie/PreiseAbschlaege/Tarife-table.html', 'bund'),
  (302, 3, 'Steuern, Abgaben und Umlagen machen einen großen Teil des Strompreises aus', 'https://www.bundesnetzagentur.de/DE/Vportal/Energie/PreiseAbschlaege/Tarife-table.html', 'bund'),
  (303, 3, 'Rund 70 % der Energie wird importiert, vor allem Öl, Gas und Steinkohle', 'https://www.umweltbundesamt.de/daten/umweltzustand-trends/energie/primaerenergiegewinnung-importe', 'bund'),
  (401, 4, 'Zu wenige Lehrkräfte: Kurzfristig liegt das Angebot deutlich unter dem Einstellungsbedarf', 'https://www.kmk.org/downloads-dokumente/statistik/schulstatistik/lehrkraefteeinstellungsbedarf-und-angebot.html', 'land'),
  (402, 4, 'Großer Sanierungsstau bei Schulgebäuden (rund 68 Mrd. Euro, größter Posten der Kommunen)', 'https://www.bundestag.de/resource/blob/1157306/KfW-Kommunalpanel-2025.pdf', 'land'),
  (403, 4, 'Wachsende Lernrückstände: Ein Drittel der Neuntklässler verfehlt den Mindeststandard in Mathematik', 'https://www.iqb.hu-berlin.de/de/schule/sekundarstufe-i/bildungstrend/2024/', 'land'),
  (404, 4, 'Viele Kinder haben schon vor der Einschulung Sprachförderbedarf; die Länder erfassen und fördern das sehr unterschiedlich', 'https://www.bildungsbericht.de/de/bildungsberichte-seit-2006/bildungsbericht-2024/pdf-dateien-2024/bildungsbericht-2024-kapitel-c.pdf', 'land'),
  (405, 4, 'Der Schulerfolg hängt stark von der sozialen Herkunft ab; sozial benachteiligte Jugendliche fallen seit 2018 weiter zurück', 'https://www.iqb.hu-berlin.de/de/schule/sekundarstufe-i/bildungstrend/2024/', 'land'),
  (501, 5, 'Die Industrie verliert an Wettbewerbsfähigkeit: überdurchschnittlich gestiegene Energiepreise und Lohnstückkosten, dazu hohe wirtschaftspolitische Unsicherheit und geopolitische Veränderungen', 'https://www.sachverstaendigenrat-wirtschaft.de/fileadmin/dateiablage/gutachten/jg202526/JG202526_Kurzfassung.pdf', 'bund'),
  (502, 5, 'Strukturwandel: Die Industrie baut Stellen ab, neue Jobs entstehen vor allem in anderen Branchen', 'https://iab.de/presseinfo/iab-prognose-fuer-2026-2027-erwerbstaetigkeit-schrumpft-trotz-besserer-konjunktur/', 'bund'),
  (503, 5, 'Löhne in Ostdeutschland liegen weiterhin deutlich unter denen im Westen', 'https://www.destatis.de/DE/Themen/Querschnitt/35-Jahre-Deutsche-Einheit/Vermoegen-Einkommen/Textbausteine/01_verdienstunterschiede.html', 'bund'),
  (504, 5, 'Zu wenig Investitionen: Für Verkehr, Bildung, Kommunen und Klimaschutz fehlen über zehn Jahre rund 600 Mrd. Euro zusätzliche öffentliche Investitionen', 'https://www.iwkoeln.de/fileadmin/user_upload/Studien/policy_papers/PDF/2024/IW-Policy-Paper_2024-Investitionsbedarfe.pdf', 'bund'),
  (505, 5, 'Hohe Bürokratiekosten: Unternehmen tragen jährlich rund 64 Mrd. Euro Kosten für Berichts- und Informationspflichten', 'https://www.normenkontrollrat.bund.de/Webs/NKR/SharedDocs/Downloads/DE/Jahresberichte/2025-jahresbericht.pdf?__blob=publicationFile&v=5', 'bund'),
  (506, 5, 'Mehr zu arbeiten lohnt sich für Menschen im Bürgergeld oft kaum, weil der Hinzuverdienst größtenteils angerechnet wird', 'https://www.bmas.de/DE/Service/Publikationen/Forschungsberichte/fb-629-erwerbstaetigenfreibetraege.html', 'bund'),
  (507, 5, 'Nur knapp die Hälfte der Beschäftigten (49 %) arbeitet in einem tarifgebundenen Betrieb', 'https://www.destatis.de/DE/Presse/Pressemitteilungen/2025/03/PD25_109_623.html', 'bund'),
  (601, 6, 'Zahl der Neuankommenden und Kapazitäten vor Ort passen vielerorts nicht zusammen: Unterbringung bleibt für die meisten Kommunen herausfordernd, Ausländerbehörden sind besonders stark belastet', 'https://mediendienst-integration.de/fileadmin/Dateien/EXPERTISE_FLUECHTLINGSAUFNAHME_IN_DEN_KOMMUNEN_MEDIENDIENST_INTEGRATION_NOV_2025_FINAL.pdf', 'land'),
  (602, 6, 'Asyl- und Gerichtsverfahren dauern lange (im Schnitt rund anderthalb Jahre bis zur rechtskräftigen Entscheidung)', 'https://www.bundestag.de/presse/hib/kurzmeldungen-1145824', 'bund'),
  (603, 6, 'Sprachkurse, Anerkennung von Abschlüssen und Zugang zum Arbeitsmarkt dauern lange', 'https://iab-forum.de/10-jahre-fluchtmigration-2015-was-integration-foerdert-und-was-sie-bremst/', 'bund'),
  (604, 6, 'Viele Ausreisepflichtige werden nicht zurückgeführt, etwa wegen fehlender Papiere', 'https://mediendienst-integration.de/fluechtlinge/abschiebungen/warum-werden-ausreisepflichtige-personen-nicht-abgeschoben/', 'bund'),
  (605, 6, 'Die EU-Zuständigkeitsregeln (Dublin) greifen kaum: 2025 wurde nur rund jede siebte von Deutschland beantragte Überstellung vollzogen', 'https://www.bundestag.de/presse/hib/kurzmeldungen-1161094', 'bund'),
  (606, 6, 'Viele Menschen leben jahrelang nur geduldet: Rund 41 % der gut 180.000 Geduldeten sind seit mehr als fünf Jahren in Deutschland', 'https://mediendienst-integration.de/fluechtlinge/duldung/wie-viele-personen-haben-eine-duldung/', 'bund'),
  (701, 7, 'Immer weniger Beitragszahlende kommen auf eine Rentnerin oder einen Rentner', 'https://www.demografie-portal.de/DE/Fakten/altersrentner-beitragszahler.html', 'bund'),
  (702, 7, 'Niedrige Löhne und Lücken im Erwerbsleben (z. B. Arbeitslosigkeit) führen zu niedrigen Rentenansprüchen', 'https://www.diw.de/sixcms/detail.php?id=diw_01.c.402060.de', 'bund'),
  (703, 7, 'Viele Beschäftigte haben keine betriebliche Altersvorsorge, vor allem in kleinen Betrieben', 'https://www.bpb.de/themen/soziale-lage/rentenpolitik/291012/empirische-befunde-zur-betrieblichen-altersversorgung/', 'bund'),
  (801, 8, 'Rund 21 Millionen Menschen fehlt ein gutes Grundangebot an Bus und Bahn, besonders auf dem Land', 'https://www.agora-verkehrswende.de/aktuelles/oev-atlas-zeigt-grosse-unterschiede-beim-bus-und-bahnangebot', 'land'),
  (802, 8, 'Marodes, überaltertes Schienennetz mit wachsendem Nachholbedarf', 'https://www.bundesrechnungshof.de/fileadmin/import/SharedDocs/Downloads/DE/Berichte/2025/evaluation-luf-3_volltext-evaluation-luf-3_volltext.pdf', 'bund'),
  (803, 8, 'Zu wenige Bus- und Straßenbahnfahrerinnen und -fahrer; viele Stellen bleiben unbesetzt', 'https://www.kofa.de/daten-und-fakten/studien/fachkraeftereport-juni-2025/', 'land'),
  (901, 9, 'Unsicherheit ballt sich an bestimmten Orten: nachts fühlen sich viele an Bahnhöfen und in Parks unsicher', 'https://www.bka.de/DE/Presse/Listenseite_Pressemitteilungen/2026/Presse2026/260420_PM_PKS_SKiD.html', 'land'),
  (902, 9, 'Überlastete Strafjustiz: Rund eine Million offene Ermittlungsverfahren, Verfahren dauern lange', 'https://www.destatis.de/DE/Presse/Pressemitteilungen/2025/10/PD25_360_2421.html', 'land'),
  (903, 9, 'Junge Menschen werden häufiger Opfer von Gewalt; die Zahl tatverdächtiger Kinder steigt', 'https://www.bka.de/DE/Presse/Listenseite_Pressemitteilungen/2026/Presse2026/260420_PM_PKS_SKiD.html', 'land'),
  (1001, 10, 'Zu wenige Pflegekräfte; bis 2049 fehlen je nach Szenario 280.000 bis 690.000', 'https://www.destatis.de/DE/Presse/Pressemitteilungen/2024/01/PD24_033_23_12.html', 'bund'),
  (1002, 10, 'Steigende Eigenanteile im Pflegeheim (im ersten Jahr im Schnitt über 3.300 Euro im Monat)', 'https://www.vdek.com/presse/pressemitteilungen/2026/stationaere-pflege-eigenanteile-juli-2026.html', 'bund'),
  (1003, 10, 'Durch die Alterung steigt die Zahl der Pflegebedürftigen deutlich', 'https://www.destatis.de/DE/Presse/Pressemitteilungen/2023/03/PD23_124_12.html', 'bund'),
  (1004, 10, 'Pflegende Angehörige tragen die Hauptlast; Entlastungsangebote werden wenig genutzt', 'https://www.zqp.de/thema/entlastung-pflegende/', 'bund')
on conflict (id) do update set thema_id = excluded.thema_id, beschreibung = excluded.beschreibung,
  quelle_url = excluded.quelle_url, ebene = excluded.ebene;

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf) values
  (4001, 4, 11, null, 'Entwicklungsstand aller Drei- bis Vierjährigen nach einheitlichen Standards erfassen', '{404}', 1, 2, null, 'Eine frühe Diagnose ist Voraussetzung für Förderung, bewirkt allein aber noch keine. Einheitliche Standards brauchen die Zustimmung der Länder.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=65', null, 'gemischt', '2026-09-28', false, true),
  (4002, 4, 11, null, 'Kinder mit Sprachförderbedarf zu einem Vorschulprogramm verpflichten; Bundesprogramm Sprach-Kitas neu starten', '{404}', 2, 2, null, 'Verbindliche Förderung vor der Einschulung setzt direkt am Sprachförderbedarf an; Studien zu Sprachförderprogrammen zeigen unterschiedlich starke Effekte. Die Pflicht müssen die Länder regeln, das Bundesprogramm ist finanzierbar.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=65', null, 'gemischt', '2026-09-28', false, true),
  (4003, 4, 11, null, 'Verbindliche Vergleichsarbeiten und Lernstandserhebungen; bundesweit vergleichbares Abitur', '{403}', 1, 1, null, 'Lernstandserhebungen machen Rückstände sichtbar, beheben sie aber nicht selbst; die Forschung zu Wirkungen von Leistungsvergleichen ist uneinheitlich. Das regeln allein die Länder.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=65', null, 'gemischt', '2026-09-28', false, true),
  (4004, 4, 11, null, 'Ganztagsangebote für Grundschulkinder ausbauen, mit Schwerpunkt auf Lesen, Schreiben und Rechnen', '{403,405}', 1, 3, null, 'Ganztag kann Kinder aus benachteiligten Familien unterstützen, Effekte auf Leistungen hängen laut Studien stark von der Qualität ab. Der Bund fördert den Ausbau bereits.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=65', null, 'gemischt', '2026-09-28', false, true),
  (4011, 4, 12, null, 'Fachkräfteoffensive für Kitas und Schulen mit allen Ländern: mehr Ausbildungsplätze, Quereinstieg, multiprofessionelle Teams', '{401}', 2, 2, null, 'Mehr Ausbildungskapazität und Quereinstieg setzen am Lehrkräftemangel an, wirken aber erst mittelfristig; die Qualität des Quereinstiegs ist umstritten. Braucht eine Vereinbarung mit allen Ländern.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=15', null, 'gemischt', '2026-09-28', false, true),
  (4012, 4, 12, null, 'Entwicklungsstand aller Kinder mit vier Jahren und bei der Einschulung feststellen, bei Bedarf verbindliche Förderung', '{404}', 2, 2, null, 'Frühe Feststellung mit verbindlichem Förderangebot setzt direkt am Sprachförderbedarf an; Studien zeigen unterschiedlich starke Effekte. Umsetzung liegt bei den Ländern.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=15', null, 'gemischt', '2026-09-28', false, true),
  (4013, 4, 12, null, 'Startchancenprogramm an Schulen schrittweise ausbauen und eines für Kitas in benachteiligten Lagen schaffen', '{405,403}', 2, 2, null, 'Geld gezielt nach sozialer Lage zu verteilen setzt an der Kopplung von Herkunft und Schulerfolg an; die Evaluation des Programms läuft noch, internationale Erfahrungen sind gemischt. Ausbau braucht zusätzliche Mittel von Bund und Ländern.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=15', null, 'gemischt', '2026-09-28', false, true),
  (4014, 4, 12, null, 'Schuldenregel reformieren, damit Investitionen etwa in Schulgebäude möglich werden; auch Länder sollen Kredite aufnehmen dürfen', '{402}', 2, 1, null, 'Mehr Investitionsspielraum kann den Sanierungsstau abbauen, wenn das Geld bei Ländern und Kommunen ankommt. Die Reform erfordert eine Grundgesetzänderung mit Zweidrittelmehrheit.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=17', null, 'belegt', '2026-09-28', false, true),
  (4015, 4, 12, null, 'Gesundes, kostenloses Mittagessen für alle Kita-Kinder und Schülerinnen und Schüler, gemeinsam mit den Ländern', '{405}', 1, 2, null, 'Kostenfreies Essen entlastet benachteiligte Familien; Studien finden teils positive, meist kleine Effekte auf Lernen. Finanzierung mit den Ländern ist aufwendig.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=27', null, 'gemischt', '2026-09-28', false, true),
  (4021, 4, 13, null, '„Zukunftsinvestitionsprogramm Bildung“ mit Ländern und Kommunen, unter anderem für moderne, sanierte Schulgebäude', '{402}', 2, 2, null, 'Investitionsmittel setzen direkt am Sanierungsstau an; der Umfang ist nicht beziffert. Der Bund kann Schulbau nur über Finanzhilfen mitfinanzieren.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=77', null, 'belegt', '2026-09-28', false, true),
  (4022, 4, 13, null, 'Mehr Stellen für Schulsozialarbeit, Schulpsychologie und Inklusion; Schwerpunkt auf Basiskompetenzen', '{403}', 2, 1, null, 'Ein Fokus auf Basiskompetenzen und Unterstützung durch Fachpersonal setzt an Lernrückständen an; die Wirkung multiprofessioneller Teams ist unterschiedlich belegt. Stellen schaffen die Länder, und Fachpersonal ist knapp.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=77', null, 'gemischt', '2026-09-28', false, true),
  (4023, 4, 13, null, 'Länder bei der Lehrkräftegewinnung unterstützen: duale Studiengänge, Ein-Fach-Lehrkräfte, Wege für Quer- und Seiteneinstieg', '{401}', 2, 2, null, 'Neue Zugangswege erhöhen das Angebot an Lehrkräften, wirken aber erst mittelfristig; die Qualität des Quereinstiegs ist umstritten. Umsetzung liegt bei den Ländern, der Bund kann unterstützen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=77', null, 'gemischt', '2026-09-28', false, true),
  (4024, 4, 13, null, 'Bildungsmittel nach tatsächlichem Bedarf statt nach Königsteiner Schlüssel verteilen; Bildungsoffensive für mehr Schulen', '{405}', 2, 2, null, 'Bedarfsorientierte Verteilung lenkt Mittel zu Schulen mit vielen benachteiligten Kindern; internationale Erfahrungen damit sind gemischt. Braucht Einigung mit den Ländern.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=77', null, 'gemischt', '2026-09-28', false, true),
  (4025, 4, 13, null, 'Sprachförderung als durchgängiger Prozess von der Kita bis in die Ausbildung', '{404}', 1, 2, null, 'Durchgängige Sprachbildung setzt am Förderbedarf an, das Programm nennt aber kein konkretes Instrument wie Tests oder verbindliche Förderung. Umsetzung liegt bei den Ländern.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=78', null, 'gemischt', '2026-09-28', false, true),
  (4031, 4, 14, null, 'Bundesweit verpflichtende Sprachtests im Vorschulalter; bei Förderbedarf verpflichtende Sprachförderung zwei Jahre vor der Schule', '{404}', 2, 2, null, 'Verbindliche Tests mit verpflichtender Förderung setzen direkt am Sprachförderbedarf an; Studien zeigen unterschiedlich starke Effekte, ein späterer Schuleintritt ist umstritten. Umsetzung liegt bei den Ländern.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=7', null, 'gemischt', '2026-09-28', false, true),
  (4032, 4, 14, null, 'Startchancen-Programm für Kitas mit vielen sozial benachteiligten Kindern', '{405}', 2, 2, null, 'Gezielte Mittel für Kitas in benachteiligten Lagen setzen früh an der Kopplung von Herkunft und Bildungserfolg an; die Evidenz zu solchen Programmen ist gemischt. Braucht Mittel und Einigung mit den Ländern.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=7', null, 'gemischt', '2026-09-28', false, true),
  (4033, 4, 14, null, 'Sanierung der Schulgebäude; Digitalpakt 2.0 von Bund und Ländern', '{402}', 2, 1, null, 'Die Forderung setzt am Sanierungsstau an, nennt aber weder Umfang noch Finanzierung. Schulbau ist Aufgabe von Ländern und Kommunen.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=8', null, 'belegt', '2026-09-28', false, true),
  (4034, 4, 14, null, 'Lehrberuf attraktiver machen: bessere Arbeitsbedingungen, leistungsorientierte Bezahlung, duales Lehramtsstudium, Mobilitätsgarantie', '{401}', 2, 2, null, 'Attraktivere Bedingungen und ein praxisnäheres Studium können mehr Menschen für den Beruf gewinnen, wirken aber erst mittelfristig; die Mobilitätsgarantie verteilt vorhandene Lehrkräfte nur um. Umsetzung liegt bei den Ländern.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=9', null, 'gemischt', '2026-09-28', false, true),
  (4035, 4, 14, null, 'Bundesweit einheitliche Qualitätsstandards von der Kita bis zum Abschluss, Deutschland-Abitur und Notenpflicht ab Klasse 3', '{403}', 1, 1, null, 'Einheitliche Standards und Prüfungen machen Leistungen vergleichbar, beheben Rückstände aber nicht selbst; die Wirkung ist in der Forschung umstritten. Braucht eine Reform des Bildungsföderalismus.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=8', null, 'gemischt', '2026-09-28', false, true),
  (4036, 4, 14, null, 'Mehr Eigenständigkeit für Schulen mit frei einsetzbarem Chancenbudget', '{403}', 1, 2, null, 'Mehr Autonomie kann Schulen helfen, auf Rückstände zu reagieren; Studien zeigen positive Effekte vor allem zusammen mit Leistungsvergleichen. Das Budget ist nicht nach sozialer Lage gezielt.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=9', null, 'gemischt', '2026-09-28', false, true),
  (4041, 4, 15, null, 'Bedarfsorientierte Vorschule, damit alle Kinder dem Unterricht folgen können', '{404}', 2, 2, null, 'Eine Vorschule für Kinder mit Rückständen setzt direkt am Sprachförderbedarf an; Studien zu Vorschulprogrammen zeigen unterschiedlich starke Effekte. Umsetzung liegt bei den Ländern.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=160', null, 'gemischt', '2026-09-28', false, true),
  (4042, 4, 15, null, 'Verpflichtender Deutschunterricht für Kinder, die nicht genug Deutsch für den Regelunterricht sprechen', '{404}', 2, 2, null, 'Gezielter Deutschunterricht setzt am Sprachförderbedarf an; ob getrennter oder integrierter Unterricht besser wirkt, ist in der Forschung umstritten. Umsetzung liegt bei den Ländern.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=162', null, 'gemischt', '2026-09-28', false, true),
  (4043, 4, 15, null, 'Klassenstärken an allen Schulformen verringern', '{403}', 1, 1, null, 'Kleinere Klassen helfen laut Studien vor allem in den ersten Schuljahren, sonst sind die Effekte gering. Sie brauchen deutlich mehr Lehrkräfte, die schon jetzt fehlen.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=159', null, 'gemischt', '2026-09-28', false, true),
  (4044, 4, 15, null, 'Bildungsstandards aller Schulformen anheben statt Leistungsanforderungen zu senken', '{403}', 1, 1, null, 'Höhere Standards benennen ein Ziel, sagen aber nicht, wie Rückstände aufgeholt werden. Die Standards legen allein die Länder in der Kultusministerkonferenz fest.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=159', null, 'offen', '2026-09-28', false, true),
  (4051, 4, 16, null, 'Vertretungsreserve von zehn Prozent; Anerkennung zugewanderter Lehrkräfte und Ausbildung von Quer- und Seiteneinsteigern', '{401}', 2, 2, null, 'Anerkennung und Quereinstieg erhöhen das Angebot an Lehrkräften; eine Vertretungsreserve setzt voraus, dass zusätzliche Lehrkräfte gefunden werden. Umsetzung liegt bei den Ländern.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=38', null, 'gemischt', '2026-09-28', false, true),
  (4052, 4, 16, null, '100-Milliarden-Euro-Sondervermögen des Bundes für Sanierung und Modernisierung von Bildungseinrichtungen, später Vermögensteuer', '{402}', 2, 1, null, 'Ein großes Investitionsprogramm setzt direkt am Sanierungsstau an. Ein kreditfinanziertes Sondervermögen und die Vermögensteuer sind rechtlich und politisch mit großen Hürden verbunden.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=38', null, 'belegt', '2026-09-28', false, true),
  (4053, 4, 16, null, 'Kostenlose Lernmittel, Verpflegung und Schülerbeförderung', '{405}', 1, 2, null, 'Kostenfreiheit entlastet benachteiligte Familien; Wirkungen auf den Schulerfolg sind meist klein. Braucht Mittel von Bund, Ländern und Kommunen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=38', null, 'gemischt', '2026-09-28', false, true),
  (4054, 4, 16, null, 'Hausaufgaben abschaffen, Üben findet in der Schule statt', '{405}', 1, 1, null, 'Üben in der Schule kann Unterschiede durch häusliche Unterstützung verringern; Hausaufgaben haben laut Studien in höheren Klassen aber positive Effekte. Regelungen dazu treffen die Länder.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=38', null, 'gemischt', '2026-09-28', false, true),
  (4055, 4, 16, null, 'Eine ganztägige Gemeinschaftsschule für alle statt des gegliederten Schulsystems', '{405}', 2, 1, null, 'Längeres gemeinsames Lernen soll die Kopplung von Herkunft und Schulerfolg verringern; internationale Studien stützen das teilweise, deutsche Vergleiche sind uneinheitlich. Die Schulstruktur bestimmen die Länder.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=39', null, 'gemischt', '2026-09-28', false, true),
  (4056, 4, 16, null, 'Mehr Pädagoginnen und Pädagogen pro Klasse; Schulpsychologie und Sozialarbeit an jeder Schule', '{403}', 2, 1, null, 'Mehr Personal pro Klasse ermöglicht individuelle Förderung; die Wirkung ist unterschiedlich belegt. Es braucht zusätzliches Personal, das schon jetzt fehlt.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=39', null, 'gemischt', '2026-09-28', false, true),
  (4057, 4, 16, null, 'Bundesprogramm für Lehrkräfte in Deutsch als Zweitsprache und Sprachkurse auch für Eltern und Geschwister', '{404}', 2, 2, null, 'Mehr qualifizierte Sprachförderung in Schulen und für Familien setzt am Förderbedarf an; Studien zeigen unterschiedlich starke Effekte. Ein Bundesprogramm ist mit den Ländern umsetzbar.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=39', null, 'gemischt', '2026-09-28', false, true),
  (4061, 4, 17, null, 'Länder bei der Ausbildung von mehr Lehrkräften unterstützen; duale Lehrerausbildung; bessere Bedingungen für Seiteneinsteiger; Entlastung durch Unterstützungsteams', '{401}', 2, 2, null, 'Mehr Ausbildung und Seiteneinstieg setzen am Lehrkräftemangel an, wirken aber erst mittelfristig; die Qualität des Seiteneinstiegs ist umstritten. Umsetzung liegt bei den Ländern, der Bund kann unterstützen.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=25', null, 'gemischt', '2026-09-29', false, true),
  (4062, 4, 17, null, 'Investitionen unter anderem in Schulen aus der Schuldenbremse ausklammern', '{402}', 2, 1, null, 'Mehr Investitionsspielraum kann den Sanierungsstau abbauen, wenn das Geld bei Ländern und Kommunen ankommt. Die Änderung der Schuldenbremse erfordert eine Grundgesetzänderung mit Zweidrittelmehrheit.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=15', null, 'belegt', '2026-09-29', false, true),
  (4063, 4, 17, null, 'Investitionsprogramm „Kinder und Bildung“ für marode Bildungs- und Betreuungseinrichtungen in Städten und Gemeinden', '{402}', 2, 2, null, 'Investitionsmittel setzen direkt am Sanierungsstau an; der Umfang ist nicht beziffert. Der Bund kann Schulbau nur über Finanzhilfen mitfinanzieren.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=32', null, 'belegt', '2026-09-29', false, true),
  (4064, 4, 17, null, 'Verpflichtender Deutschtest ab drei Jahren; bei Defiziten verpflichtender, beitragsfreier Kita-Besuch mit Sprachbildung', '{404}', 2, 2, null, 'Frühe verbindliche Tests mit verpflichtender Förderung setzen direkt am Sprachförderbedarf an; Studien zeigen unterschiedlich starke Effekte. Umsetzung liegt bei den Ländern.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=24', null, 'gemischt', '2026-09-29', false, true),
  (4065, 4, 17, null, 'Ganztagsschulen sowie Hort- und Hausaufgabenbetreuung ausbauen, damit Kinder weniger von der Unterstützung der Eltern abhängen', '{405}', 1, 2, null, 'Ganztag kann Kinder aus benachteiligten Familien unterstützen, Effekte auf Leistungen hängen laut Studien stark von der Qualität ab. Der Bund fördert bisher nur den Ganztag an Grundschulen.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=24', null, 'gemischt', '2026-09-29', false, true),
  (4066, 4, 17, null, 'Längeres gemeinsames Lernen und ein durchlässiges Schulsystem statt früher Aufteilung nach Klasse 4', '{405}', 2, 1, null, 'Später aufzuteilen soll die Kopplung von Herkunft und Schulerfolg verringern; internationale Studien stützen das teilweise, deutsche Vergleiche sind uneinheitlich. Die Schulstruktur bestimmen allein die Länder.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=24', null, 'gemischt', '2026-09-29', false, true),
  (4067, 4, 17, null, 'Grundschule auf Lesen, Schreiben und Rechnen konzentrieren; Handys und Tablets bis Ende der Grundschule aus dem Unterricht', '{403}', 1, 1, null, 'Ein Fokus auf Basiskompetenzen setzt an Lernrückständen an; zur Wirkung von Geräteverboten ist die Forschung uneinheitlich. Das regeln allein die Länder.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=24', null, 'gemischt', '2026-09-29', false, true),
  (4068, 4, 17, null, 'Kostenloses, gesundes Mittagessen in Kitas und Schulen', '{405}', 1, 2, null, 'Kostenfreies Essen entlastet benachteiligte Familien; Studien finden teils positive, meist kleine Effekte auf Lernen. Finanzierung mit den Ländern ist aufwendig.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=31', null, 'gemischt', '2026-09-29', false, true);

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf) values
  (4, 11, null, 'massnahmen', null, '2026-09-28', true),
  (4, 12, null, 'massnahmen', null, '2026-09-28', true),
  (4, 13, null, 'massnahmen', null, '2026-09-28', true),
  (4, 14, null, 'massnahmen', null, '2026-09-28', true),
  (4, 15, null, 'massnahmen', null, '2026-09-28', true),
  (4, 16, null, 'massnahmen', null, '2026-09-28', true),
  (4, 17, null, 'massnahmen', null, '2026-09-29', true);
