-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 18 „Hitze und Unwetter“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 18;
delete from public.abdeckung where thema_id = 18;
delete from public.pruef_einheiten where thema_id = 18;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (7932, 18, 'CO2-Bepreisung bzw. Emissionshandel für Verkehr und Gebäude stärken (Bund)', 'CO2-Preise senken Emissionen nachweislich (Metaanalyse: im Mittel rund 10 %). Auf Hitze in Deutschland wirkt nationaler Klimaschutz aber nur als kleiner Beitrag zum globalen Klimaschutz und mit großer Verzögerung.', 'belegt', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11099057/', 'bund', null, true, 'blind'),
  (7933, 18, 'Verbindliche Sektorziele und Nachsteuerungspflicht im Klimaschutzgesetz (Bund)', 'Verbindliche Sektorziele erhöhen den Druck zum Nachsteuern und sind per Gesetzesänderung umsetzbar; ihre eigene Wirkung ist kaum belegt, und auf die Hitze in Deutschland wirkt nationaler Klimaschutz nur langfristig und gering.', 'offen', null, 'bund', null, true, 'blind'),
  (7934, 18, 'Ausbau erneuerbarer Strom- und Wärmeversorgung fördern (Bund)', 'Erneuerbare vermieden 2024 laut UBA rund 259 Mio. t CO2-Äquivalente; Förderprogramme bestehen. Auf Hitzetage in Deutschland wirkt das nur als kleiner Teil des globalen Klimaschutzes und mit Verzögerung.', 'belegt', 'https://www.umweltbundesamt.de/publikationen/emissionsbilanz-erneuerbarer-energietrager-2024', 'bund', null, true, 'blind'),
  (7935, 18, 'Abscheidung und Speicherung von CO2 (CCS/CCU) ermöglichen und fördern (Bund)', 'Seit Ende 2025 ist kommerzielles CCS rechtlich möglich; es kann schwer vermeidbare Industrieemissionen senken. Dagegen: Infrastruktur braucht 7 bis 10 Jahre, Kosten und Umfang sind unsicher; Wirkung auf Hitze gering.', 'gemischt', 'https://www.bundesregierung.de/breg-de/aktuelles/speicherung-von-kohlendioxid-2376946', 'bund', null, true, 'blind'),
  (7936, 18, 'Kohleausstieg aussetzen oder Abschaltung von Kohlekraftwerken aufschieben (Bund)', 'Längerer Kohlebetrieb erhöht die Emissionen gegenüber einem Ausstieg (Studien: deutliche Minderung durch Ausstieg) und hilft nicht gegen Hitze; per Gesetz änderbar, aber durch CO2-Preise im EU-Emissionshandel wirtschaftlich fraglich.', 'belegt', 'https://www.ewi.uni-koeln.de/en/news/neue-ewi-studie-kohleausstieg-ermoeglicht-erreichung-der-klimaziele-2030/', 'bund', null, true, 'blind'),
  (7937, 18, 'Nationalen CO2-Preis abschaffen (Bund)', 'Entfernt ein nachweislich emissionsmindernd wirkendes Instrument und hilft nicht gegen Hitze. National möglich, ab 2028 greift für Verkehr und Gebäude aber ohnehin der EU-Emissionshandel.', 'belegt', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11099057/', 'bund', null, true, 'blind'),
  (7938, 18, 'CO2-Flottenvorgaben für Neuwagen (Verbrenner-Aus 2035) aufheben (Bund)', 'Lockert eine Emissionsvorgabe und setzt an keiner Ursache im Sinne des Ziels an. Die Vorgabe ist EU-Recht; Deutschland kann sie nicht allein aufheben, sondern nur im EU-Verfahren darauf hinwirken.', 'offen', null, 'bund', null, true, 'blind'),
  (7939, 18, 'Heizungsvorgaben im Gebäudeenergiegesetz abschaffen (Bund)', 'Lockert eine Vorgabe zur Emissionsminderung bei Heizungen und hilft nicht gegen Hitze oder Unwetterschäden. Per Bundesgesetz änderbar, EU-Gebäuderichtlinie setzt aber Grenzen.', 'offen', null, 'bund', null, true, 'blind'),
  (7940, 18, 'Bundesförderung für Stadtgrün, Entsiegelung und hitzeangepasste Städte (Bund)', 'Parks und Bäume kühlen nachweislich (große Parks 1 bis 2 °C im Umfeld); der Bund fördert Städtebau bereits. Dagegen: Wirkung bleibt lokal und hängt von Umsetzung in den Kommunen ab.', 'belegt', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6458494/', 'bund', null, true, 'blind'),
  (7941, 18, 'Allgemeine Zusage zu Begrünung und Entsiegelung ohne konkretes Instrument (Bund)', 'Begrünung und Entsiegelung wirken nachweislich gegen Hitze und Abfluss; die Zusage nennt aber weder Instrument noch Mittel, daher ist kaum eine Verbesserung absehbar.', 'belegt', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6458494/', 'bund', null, true, 'blind'),
  (7942, 18, 'Bundesmittel für Hochwasserschutz: Deiche, Rückhalteräume und Auen (Bund)', 'Rückhalteräume und Auen dämpfen Hochwasserscheitel nachweislich, der Bund fördert Hochwasserschutz bereits mit. Dagegen: Deiche verlagern Risiken teils flussabwärts und ändern das Bauen in Überschwemmungsgebieten nicht.', 'belegt', 'https://www.umweltbundesamt.de/hochwasser-durch-renaturierung-entschaerfen', 'bund', null, true, 'blind')
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 18 and id not in (7932, 7933, 7934, 7935, 7936, 7937, 7938, 7939, 7940, 7941, 7942);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (7943, 18, 11, null, 'Flächendeckende Pflichtversicherung für Elementarschäden einführen', '{1806}', null, 3, 2, null, 'Setzt direkt an der Versicherungslücke an: Frankreich erreicht mit verpflichtender Deckung rund 98 %, Deutschland rund 50 %. Verfassungsrechtlich laut Justizministerkonferenz möglich; Prämien in Risikogebieten bleiben strittig.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=25', 'https://www.bundestag.de/dokumente/textarchiv/2024/kw11-pa-recht-elementarschadenversicherung-991898', 'belegt', '2026-10-04', false, true, 'blind'),
  (7944, 18, 11, null, 'Küsten- und Hochwasserschutz priorisieren und von der Ausgleichspflicht für solche Maßnahmen wegkommen', '{1805}', null, 1, 2, null, 'Weniger Ausgleichspflichten können Hochwasserschutzbauten beschleunigen. Dagegen: Kein zusätzliches Geld oder Vorhaben, Bauen in Überschwemmungsgebieten bleibt unberührt, EU-Naturschutzrecht begrenzt den Spielraum.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=25', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7945, 18, 11, null, 'Flächenversiegelung reduzieren und Flächen klüger nutzen', '{1804}', 7941, 1, 2, null, 'Begrünung und Entsiegelung wirken nachweislich gegen Hitze und Abfluss; die Zusage nennt aber weder Instrument noch Mittel, daher ist kaum eine Verbesserung absehbar.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=26', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6458494/', 'belegt', '2026-10-04', false, true, 'blind'),
  (7946, 18, 11, null, 'Städte und Gemeinden bei Wassermanagement und verstärkter Begrünung unterstützen', '{1803}', 7941, 1, 2, null, 'Begrünung und Entsiegelung wirken nachweislich gegen Hitze und Abfluss; die Zusage nennt aber weder Instrument noch Mittel, daher ist kaum eine Verbesserung absehbar.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=77', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6458494/', 'belegt', '2026-10-04', false, true, 'blind'),
  (7947, 18, 11, null, 'CO2-Bepreisung zum Leitinstrument ausbauen, Einnahmen zurückgeben', '{1801,1802}', 7932, 1, 2, null, 'CO2-Preise senken Emissionen nachweislich (Metaanalyse: im Mittel rund 10 %). Auf Hitze in Deutschland wirkt nationaler Klimaschutz aber nur als kleiner Beitrag zum globalen Klimaschutz und mit großer Verzögerung.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=24', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11099057/', 'belegt', '2026-10-04', false, true, 'blind'),
  (7948, 18, 11, null, 'Heizungsgesetz abschaffen, stattdessen technologieoffen emissionsarme Wärme fördern', '{1801,1802}', 7939, 0, 2, null, 'Lockert eine Vorgabe zur Emissionsminderung bei Heizungen und hilft nicht gegen Hitze oder Unwetterschäden. Per Bundesgesetz änderbar, EU-Gebäuderichtlinie setzt aber Grenzen.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=22', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7949, 18, 11, null, 'Verbrenner-Verbot rückgängig machen', '{1801,1802}', 7938, 0, 1, null, 'Lockert eine Emissionsvorgabe und setzt an keiner Ursache im Sinne des Ziels an. Die Vorgabe ist EU-Recht; Deutschland kann sie nicht allein aufheben, sondern nur im EU-Verfahren darauf hinwirken.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=74', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7950, 18, 11, null, 'Kein weiteres endgültiges Abschalten von Kohlekraftwerken, bevor Ersatz gebaut ist', '{1801,1802}', 7936, 0, 2, null, 'Längerer Kohlebetrieb erhöht die Emissionen gegenüber einem Ausstieg (Studien: deutliche Minderung durch Ausstieg) und hilft nicht gegen Hitze; per Gesetz änderbar, aber durch CO2-Preise im EU-Emissionshandel wirtschaftlich fraglich.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=21', 'https://www.ewi.uni-koeln.de/en/news/neue-ewi-studie-kohleausstieg-ermoeglicht-erreichung-der-klimaziele-2030/', 'belegt', '2026-10-04', false, true, 'blind'),
  (7951, 18, 11, null, 'Moorschutz intensivieren und Anreize für Wiedervernässung geben', '{1801,1802}', null, 1, 2, null, 'Entwässerte Moore verursachen rund 7,5 % der deutschen Emissionen; Wiedervernässung senkt sie deutlich. Dagegen: Umsetzung braucht Einigung mit Eigentümern und Zeit; die Wirkung auf Hitze bleibt gering.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=25', 'https://www.bundesumweltministerium.de/faq/warum-ist-die-wiedervernaessung-von-mooren-so-wichtig', 'belegt', '2026-10-04', false, true, 'blind'),
  (7952, 18, 11, null, 'Rahmenbedingungen für Kohlenstoffabscheidung, -nutzung und -speicherung samt Transportinfrastruktur schaffen', '{1801,1802}', 7935, 1, 3, null, 'Seit Ende 2025 ist kommerzielles CCS rechtlich möglich; es kann schwer vermeidbare Industrieemissionen senken. Dagegen: Infrastruktur braucht 7 bis 10 Jahre, Kosten und Umfang sind unsicher; Wirkung auf Hitze gering.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=24', 'https://www.bundesregierung.de/breg-de/aktuelles/speicherung-von-kohlendioxid-2376946', 'gemischt', '2026-10-04', false, true, 'blind'),
  (7953, 18, 12, null, 'Städtebauförderung zur Klimaanpassung: Begrünung, Entsiegelung (Schwammstadt) und kühlende öffentliche Räume in Städten.', '{1803}', 7940, 2, 3, null, 'Parks und Bäume kühlen nachweislich (große Parks 1 bis 2 °C im Umfeld); der Bund fördert Städtebau bereits. Dagegen: Wirkung bleibt lokal und hängt von Umsetzung in den Kommunen ab.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=34', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6458494/', 'belegt', '2026-10-04', false, true, 'blind'),
  (7954, 18, 12, null, 'Vorsorge gegen Klimafolgen wie Hitzewellen im Bevölkerungsschutz stärken.', '{1801}', null, 1, 3, null, 'Vorsorge gegen Hitzewellen im Bevölkerungsschutz ist sinnvoll und umsetzbar. Dagegen: Die Zusage nennt kein konkretes Instrument, daher ist die Wirkung kaum abschätzbar.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=46', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7955, 18, 12, null, 'Kommunale Wärmepläne für klimaneutrale Wärmeversorgung fördern.', '{1801,1802}', 7934, 1, 3, null, 'Erneuerbare vermieden 2024 laut UBA rund 259 Mio. t CO2-Äquivalente; Förderprogramme bestehen. Auf Hitzetage in Deutschland wirkt das nur als kleiner Teil des globalen Klimaschutzes und mit Verzögerung.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=33', 'https://www.umweltbundesamt.de/publikationen/emissionsbilanz-erneuerbarer-energietrager-2024', 'belegt', '2026-10-04', false, true, 'blind'),
  (7956, 18, 12, null, 'Mittel aus Aktionsprogramm Natürlicher Klimaschutz flächendeckend einsetzen, um Wälder, Moore, Flussauen und Stadtgrün zu schützen.', '{1801,1802,1803}', null, 1, 3, null, 'Das bestehende Förderprogramm stärkt Senken und Stadtgrün und ist finanziert. Dagegen: Die Mittel verteilen sich breit, der Beitrag zur Kühlung von Städten und zur Hitzevermeidung bleibt gering.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=53', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7957, 18, 12, null, 'Windkraft und Fotovoltaik konsequent ausbauen und mit Speichern einbinden.', '{1801,1802}', 7934, 1, 3, null, 'Erneuerbare vermieden 2024 laut UBA rund 259 Mio. t CO2-Äquivalente; Förderprogramme bestehen. Auf Hitzetage in Deutschland wirkt das nur als kleiner Teil des globalen Klimaschutzes und mit Verzögerung.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=34', 'https://www.umweltbundesamt.de/publikationen/emissionsbilanz-erneuerbarer-energietrager-2024', 'belegt', '2026-10-04', false, true, 'blind'),
  (7958, 18, 13, null, 'Europäischen Emissionshandel für Verkehr und Gebäude unterstützen und den CO₂-Preis als zentralen Hebel stärken', '{1801,1802}', 7932, 1, 2, null, 'CO2-Preise senken Emissionen nachweislich (Metaanalyse: im Mittel rund 10 %). Auf Hitze in Deutschland wirkt nationaler Klimaschutz aber nur als kleiner Beitrag zum globalen Klimaschutz und mit großer Verzögerung.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=38', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11099057/', 'belegt', '2026-10-04', false, true, 'blind'),
  (7959, 18, 13, null, 'Sektorverantwortung im Klimaschutzgesetz stärken, bei Zielverfehlung verbindlich nachsteuern', '{1801,1802}', 7933, 1, 3, null, 'Verbindliche Sektorziele erhöhen den Druck zum Nachsteuern und sind per Gesetzesänderung umsetzbar; ihre eigene Wirkung ist kaum belegt, und auf die Hitze in Deutschland wirkt nationaler Klimaschutz nur langfristig und gering.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=39', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7960, 18, 13, null, 'Alle verbliebenen Kohlekraftwerke ab 2030 nicht mehr befeuern, Kohleförderung beenden, fossiles Gas schrittweise reduzieren', '{1801,1802}', null, 1, 2, null, 'Ein Kohleausstieg senkt die Emissionen des Stromsektors deutlich (Studien). Dagegen: Ersatzkraftwerke und Versorgungssicherheit bis 2030 sind ungeklärt, und die Wirkung auf Hitze in Deutschland ist gering und verzögert.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=43', 'https://www.ewi.uni-koeln.de/en/news/neue-ewi-studie-kohleausstieg-ermoeglicht-erreichung-der-klimaziele-2030/', 'belegt', '2026-10-04', false, true, 'blind'),
  (7961, 18, 13, null, 'Förderung für fossilfreie Heizungen und Wärmenetze ausbauen, Energieberatung ausbauen', '{1801,1802}', 7934, 1, 3, null, 'Erneuerbare vermieden 2024 laut UBA rund 259 Mio. t CO2-Äquivalente; Förderprogramme bestehen. Auf Hitzetage in Deutschland wirkt das nur als kleiner Teil des globalen Klimaschutzes und mit Verzögerung.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=44', 'https://www.umweltbundesamt.de/publikationen/emissionsbilanz-erneuerbarer-energietrager-2024', 'belegt', '2026-10-04', false, true, 'blind'),
  (7962, 18, 13, null, 'Hochwasserschutz mit den Ländern verbessern: natürliche Überschwemmungsräume, Auen mehr Raum, Deiche und Rückhaltesysteme, beschleunigte Umsetzung', '{1805}', 7942, 2, 3, null, 'Rückhalteräume und Auen dämpfen Hochwasserscheitel nachweislich, der Bund fördert Hochwasserschutz bereits mit. Dagegen: Deiche verlagern Risiken teils flussabwärts und ändern das Bauen in Überschwemmungsgebieten nicht.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=46', 'https://www.umweltbundesamt.de/hochwasser-durch-renaturierung-entschaerfen', 'belegt', '2026-10-04', false, true, 'blind'),
  (7963, 18, 13, null, 'Städte gegen Hitzewellen und Starkregen schützen: mehr Entsiegelung, Frischluftschneisen, Gebäude- und Stadtgrün, Trinkbrunnen, Schwammstadt', '{1802,1803,1804}', 7940, 2, 3, null, 'Parks und Bäume kühlen nachweislich (große Parks 1 bis 2 °C im Umfeld); der Bund fördert Städtebau bereits. Dagegen: Wirkung bleibt lokal und hängt von Umsetzung in den Kommunen ab.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=46', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6458494/', 'belegt', '2026-10-04', false, true, 'blind'),
  (7964, 18, 13, null, 'Versicherungsschutz gegen Elementarschäden sozialverträglich ausweiten', '{1806}', null, 2, 2, null, 'Setzt an der Versicherungslücke an; Erfahrungen anderswo zeigen, dass verbindliche Modelle die Deckung stark erhöhen. Dagegen: Ohne bestimmtes Instrument (Pflicht oder Angebotsmodell) ist der Umfang der Verbesserung offen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=46', 'https://www.bundestag.de/dokumente/textarchiv/2024/kw11-pa-recht-elementarschadenversicherung-991898', 'belegt', '2026-10-04', false, true, 'blind'),
  (7965, 18, 13, null, 'Nationalen Hitzeschutzplan ausbauen und Hitzeaktionspläne in allen Kommunen', '{1802}', null, 3, 2, null, 'Hitzeschutzpläne senkten die hitzebedingte Übersterblichkeit in Europa um rund 25 %. Dagegen: Pläne in allen Kommunen kann der Bund nicht vorschreiben, nur fördern und mit Ländern vereinbaren.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=96', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12724396/', 'belegt', '2026-10-04', false, true, 'blind'),
  (7966, 18, 13, null, 'Flächenverbrauch mit neuen Instrumenten (Flächenzertifikatehandel, Baulandabgabemodell) bis 2030 auf 30 Hektar pro Tag senken', '{1804}', null, 2, 2, null, 'Ein Planspiel mit 87 Kommunen zeigte, dass Flächenzertifikate Neuversiegelung wirksam begrenzen können. Dagegen: Reale Erfahrungen fehlen, und die Einführung braucht neue Bundesregeln und Akzeptanz der Kommunen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=73', 'https://www.umweltbundesamt.de/themen/flaechenzertifikatehandel-flaechenverbauchsziele', 'offen', '2026-10-04', false, true, 'blind'),
  (7967, 18, 14, null, 'Einheitlicher europäischer Emissionshandel als Leitinstrument der Klimapolitik, mit global angestrebtem Preis für Treibhausgase', '{1801,1802}', null, 1, 1, null, 'Emissionshandel senkt Emissionen nachweislich. Dagegen: Ein einheitlicher EU-Handel hängt von EU-Entscheidungen ab, ein globaler Preis von anderen Staaten; die Wirkung auf Hitze in Deutschland ist gering.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=40', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11099057/', 'belegt', '2026-10-04', false, true, 'blind'),
  (7968, 18, 14, null, 'Nationales Klimaneutralitätsziel 2045 im Klimaschutzgesetz durch das europäische Ziel 2050 ersetzen', '{1801,1802}', null, 0, 1, null, 'Ein späteres Klimaneutralitätsziel bremst Emissionsminderung und hilft nicht gegen Hitze. Rechtlich heikel, weil das Bundesverfassungsgericht einen ausreichenden Reduktionspfad verlangt.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=40', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7969, 18, 14, null, 'Abscheidung und Speicherung von Treibhausgasen (CCS/CCU) diskriminierungsfrei als Klimaschutz-Option ermöglichen', '{1801,1802}', 7935, 1, 3, null, 'Seit Ende 2025 ist kommerzielles CCS rechtlich möglich; es kann schwer vermeidbare Industrieemissionen senken. Dagegen: Infrastruktur braucht 7 bis 10 Jahre, Kosten und Umfang sind unsicher; Wirkung auf Hitze gering.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=40', 'https://www.bundesregierung.de/breg-de/aktuelles/speicherung-von-kohlendioxid-2376946', 'gemischt', '2026-10-04', false, true, 'blind'),
  (7970, 18, 14, null, 'Heizungsgesetz vollständig auslaufen lassen; stattdessen Zertifikatehandel', '{1801,1802}', 7939, 0, 2, null, 'Lockert eine Vorgabe zur Emissionsminderung bei Heizungen und hilft nicht gegen Hitze oder Unwetterschäden. Per Bundesgesetz änderbar, EU-Gebäuderichtlinie setzt aber Grenzen.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=45', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7971, 18, 14, null, 'Faktisches Verbrenner-Verbot ab 2035 umgehend aufheben', '{1801,1802}', 7938, 0, 1, null, 'Lockert eine Emissionsvorgabe und setzt an keiner Ursache im Sinne des Ziels an. Die Vorgabe ist EU-Recht; Deutschland kann sie nicht allein aufheben, sondern nur im EU-Verfahren darauf hinwirken.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=40', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7972, 18, 14, null, 'Erneuerbare Energien ohne EEG-Subventionen für neue Anlagen vollständig in den Markt überführen', '{1801,1802}', null, 0, 2, null, 'Marktintegration kann Förderkosten senken; ohne Absicherung droht aber ein langsamerer Ausbau, der Emissionen weniger senkt. Ein Beitrag gegen Hitze ist nicht zu erwarten; EEG-Änderung möglich.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=18', null, 'gemischt', '2026-10-04', false, true, 'blind'),
  (7973, 18, 14, null, 'Bau neuer Kernkraftwerke und Wiederinbetriebnahme vorhandener rechtlich ermöglichen, ohne Subventionen', '{1801,1802}', null, 0, 1, null, 'Kernkraft ist emissionsarm, ohne Subventionen ist ein Neubau aber nicht absehbar; ob vorhandene Anlagen reaktiviert werden können, ist umstritten. In einer Wahlperiode ist keine Wirkung auf Emissionen zu erwarten.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=18', null, 'gemischt', '2026-10-04', false, true, 'blind'),
  (7974, 18, 15, null, 'Geplanten Ausstieg aus der Braunkohleverstromung nicht umsetzen, Kohlekraftwerke ausbauen.', '{1801,1802}', 7936, 0, 2, null, 'Längerer Kohlebetrieb erhöht die Emissionen gegenüber einem Ausstieg (Studien: deutliche Minderung durch Ausstieg) und hilft nicht gegen Hitze; per Gesetz änderbar, aber durch CO2-Preise im EU-Emissionshandel wirtschaftlich fraglich.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=42', 'https://www.ewi.uni-koeln.de/en/news/neue-ewi-studie-kohleausstieg-ermoeglicht-erreichung-der-klimaziele-2030/', 'belegt', '2026-10-04', false, true, 'blind'),
  (7975, 18, 15, null, 'Wiedereinstieg in die Kernenergie, bestehende Kraftwerke so schnell wie möglich wieder in Betrieb nehmen.', '{1801,1802}', null, 0, 1, null, 'Der zugleich geplante Ausbau von Kohlekraftwerken erhöht Emissionen. Eine Rückkehr zur Kernenergie wäre in einer Wahlperiode kaum wirksam, weil der Rückbau fortgeschritten ist und Betreiber eine Reaktivierung ablehnen.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=42', null, 'gemischt', '2026-10-04', false, true, 'blind'),
  (7976, 18, 15, null, 'Abgabe auf CO₂ abschaffen.', '{1801,1802}', 7937, 0, 2, null, 'Entfernt ein nachweislich emissionsmindernd wirkendes Instrument und hilft nicht gegen Hitze. National möglich, ab 2028 greift für Verkehr und Gebäude aber ohnehin der EU-Emissionshandel.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=14', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11099057/', 'belegt', '2026-10-04', false, true, 'blind'),
  (7977, 18, 15, null, 'Verbot von Gas- und Ölheizungen aufheben.', '{1801,1802}', 7939, 0, 2, null, 'Lockert eine Vorgabe zur Emissionsminderung bei Heizungen und hilft nicht gegen Hitze oder Unwetterschäden. Per Bundesgesetz änderbar, EU-Gebäuderichtlinie setzt aber Grenzen.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=14', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7978, 18, 15, null, 'Verbot des Verbrennungsmotors aufheben.', '{1801,1802}', 7938, 0, 1, null, 'Lockert eine Emissionsvorgabe und setzt an keiner Ursache im Sinne des Ziels an. Die Vorgabe ist EU-Recht; Deutschland kann sie nicht allein aufheben, sondern nur im EU-Verfahren darauf hinwirken.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=42', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7979, 18, 15, null, 'Weiteren Ausbau der Windenergie ablehnen.', '{1801,1802}', null, 0, 2, null, 'Ein Stopp des Windausbaus bremst die Verdrängung fossiler Stromerzeugung, die nachweislich Emissionen vermeidet, und hilft nicht gegen Hitze. Erfordert Änderungen an EEG und Planungsrecht.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=81', 'https://www.umweltbundesamt.de/publikationen/emissionsbilanz-erneuerbarer-energietrager-2024', 'belegt', '2026-10-04', false, true, 'blind'),
  (7980, 18, 15, null, 'Aus dem Pariser Klimaabkommen aussteigen.', '{1801,1802}', null, 0, 2, null, 'Der Austritt schwächt internationale Klimaschutzverpflichtungen und hilft nicht gegen Hitze. Rechtlich per Kündigung möglich; EU-Klimarecht bliebe bindend.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=80', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7981, 18, 16, null, 'Kitas und Schulen besser vor Hitzewellen schützen, Investitionsmittel dafür bereitstellen', '{1802}', null, 1, 2, null, 'Kinder leiden bei Hitze häufig gesundheitlich, Investitionen in Kitas und Schulen helfen ihnen. Dagegen: Die meisten Hitzetoten sind über 75; Kitas und Schulen sind Sache von Ländern und Kommunen, der Bund kann nur mitfinanzieren.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=38', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7982, 18, 16, null, 'Mehr öffentliche Parks und Grünflächen gegen die Hitze sowie öffentliche Wasserspender; Gebäude- und Flächenbegrünung ausweiten', '{1803,1802}', 7940, 2, 3, null, 'Parks und Bäume kühlen nachweislich (große Parks 1 bis 2 °C im Umfeld); der Bund fördert Städtebau bereits. Dagegen: Wirkung bleibt lokal und hängt von Umsetzung in den Kommunen ab.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=45', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6458494/', 'belegt', '2026-10-04', false, true, 'blind'),
  (7983, 18, 16, null, 'Flächenentsiegelung vorantreiben, Städte zu Schwammstädten machen und vor Flutkatastrophen schützen', '{1804}', 7941, 1, 2, null, 'Begrünung und Entsiegelung wirken nachweislich gegen Hitze und Abfluss; die Zusage nennt aber weder Instrument noch Mittel, daher ist kaum eine Verbesserung absehbar.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=45', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6458494/', 'belegt', '2026-10-04', false, true, 'blind'),
  (7984, 18, 16, null, 'Luftaustausch zwischen Stadt und Umland durch bessere Raumplanung verbessern', '{1803}', null, 2, 2, null, 'Kaltluftbahnen aus dem Umland verbessern die nächtliche Abkühlung von Städten. Dagegen: Die Planung liegt überwiegend bei Ländern und Kommunen, der Bund kann nur über Raumordnung und Baurecht beitragen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=45', 'https://www.vdi.de/news/detail/lokale-kaltluft-in-staedten-ein-wichtiger-baustein-im-zuge-der-klimaanpassung', 'belegt', '2026-10-04', false, true, 'blind'),
  (7985, 18, 16, null, 'Klimaanpassung als Gemeinschaftsaufgabe von Bund, Ländern und Kommunen definieren, Katastrophenschutz massiv aufwerten', '{1801}', null, 2, 1, null, 'Eine Gemeinschaftsaufgabe würde dauerhafte Mischfinanzierung von Anpassung durch Bund und Länder ermöglichen. Dagegen: Grundgesetzänderung mit Zweidrittelmehrheiten nötig, Wirkung hängt von späteren Mitteln ab.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=33', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7986, 18, 16, null, 'Sektorziele im Klimaschutzgesetz wiederherstellen, verbindliche Ziele und Emissionsgrenzen', '{1801,1802}', 7933, 1, 3, null, 'Verbindliche Sektorziele erhöhen den Druck zum Nachsteuern und sind per Gesetzesänderung umsetzbar; ihre eigene Wirkung ist kaum belegt, und auf die Hitze in Deutschland wirkt nationaler Klimaschutz nur langfristig und gering.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=33', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7987, 18, 16, null, 'Emissionshandel für Wärme und Verkehr (ETS-2) ablehnen, stattdessen verbindliche Klimaziele und Emissionsgrenzen', '{1801,1802}', null, 1, 1, null, 'Verbindliche Ziele und Grenzen können Emissionen senken. Dagegen: Der EU-Emissionshandel für Wärme und Verkehr ist beschlossenes EU-Recht, das Deutschland nicht allein abwählen kann; Wirkung auf Hitze gering.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=33', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7988, 18, 17, null, 'Nationalen CO2-Preis abschaffen.', '{1801,1802}', 7937, 0, 2, null, 'Entfernt ein nachweislich emissionsmindernd wirkendes Instrument und hilft nicht gegen Hitze. National möglich, ab 2028 greift für Verkehr und Gebäude aber ohnehin der EU-Emissionshandel.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=10', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11099057/', 'belegt', '2026-10-04', false, true, 'blind'),
  (7989, 18, 17, null, 'Verbrenner-Verbot zurücknehmen.', '{1801,1802}', 7938, 0, 1, null, 'Lockert eine Emissionsvorgabe und setzt an keiner Ursache im Sinne des Ziels an. Die Vorgabe ist EU-Recht; Deutschland kann sie nicht allein aufheben, sondern nur im EU-Verfahren darauf hinwirken.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=29', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7990, 18, 17, null, 'Heizungsgesetz sofort abschaffen und durch andere Regelungen ersetzen.', '{1801,1802}', 7939, 0, 2, null, 'Lockert eine Vorgabe zur Emissionsminderung bei Heizungen und hilft nicht gegen Hitze oder Unwetterschäden. Per Bundesgesetz änderbar, EU-Gebäuderichtlinie setzt aber Grenzen.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=10', null, 'offen', '2026-10-04', false, true, 'blind'),
  (7991, 18, 17, null, 'Bau von CCS- und CCU-Anlagen durch Superabschreibungen oder öffentliche Kredite fördern.', '{1801,1802}', 7935, 1, 3, null, 'Seit Ende 2025 ist kommerzielles CCS rechtlich möglich; es kann schwer vermeidbare Industrieemissionen senken. Dagegen: Infrastruktur braucht 7 bis 10 Jahre, Kosten und Umfang sind unsicher; Wirkung auf Hitze gering.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=12', 'https://www.bundesregierung.de/breg-de/aktuelles/speicherung-von-kohlendioxid-2376946', 'gemischt', '2026-10-04', false, true, 'blind'),
  (7992, 18, 17, null, 'Repowering-Programm: alte Windanlagen durch neue ersetzen.', '{1801,1802}', 7934, 1, 3, null, 'Erneuerbare vermieden 2024 laut UBA rund 259 Mio. t CO2-Äquivalente; Förderprogramme bestehen. Auf Hitzetage in Deutschland wirkt das nur als kleiner Teil des globalen Klimaschutzes und mit Verzögerung.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=11', 'https://www.umweltbundesamt.de/publikationen/emissionsbilanz-erneuerbarer-energietrager-2024', 'belegt', '2026-10-04', false, true, 'blind'),
  (7993, 18, 17, null, 'Fernwärme ausbauen und auf erneuerbare Quellen umstellen, Geothermie-Ausbauziele anheben.', '{1801,1802}', 7934, 1, 3, null, 'Erneuerbare vermieden 2024 laut UBA rund 259 Mio. t CO2-Äquivalente; Förderprogramme bestehen. Auf Hitzetage in Deutschland wirkt das nur als kleiner Teil des globalen Klimaschutzes und mit Verzögerung.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=12', 'https://www.umweltbundesamt.de/publikationen/emissionsbilanz-erneuerbarer-energietrager-2024', 'belegt', '2026-10-04', false, true, 'blind'),
  (7994, 18, 17, null, 'Mittel für Auf- und Ausbau von Deichen und Dämmen bereitstellen, Folgen von Hochwasser abmildern.', '{1805}', 7942, 2, 3, null, 'Rückhalteräume und Auen dämpfen Hochwasserscheitel nachweislich, der Bund fördert Hochwasserschutz bereits mit. Dagegen: Deiche verlagern Risiken teils flussabwärts und ändern das Bauen in Überschwemmungsgebieten nicht.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=20', 'https://www.umweltbundesamt.de/hochwasser-durch-renaturierung-entschaerfen', 'belegt', '2026-10-04', false, true, 'blind'),
  (8573, 18, 18, null, 'Naturbasierte Lösungen: Gebäudebegrünung, Entsiegelung, Schwammstadt als zentrales Konzept.', '{1804,1803}', 7941, 1, 2, null, 'Begrünung und Entsiegelung wirken nachweislich gegen Hitze und Abfluss; die Zusage nennt aber weder Instrument noch Mittel, daher ist kaum eine Verbesserung absehbar.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=76', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6458494/', 'belegt', '2026-10-07', false, true, 'blind'),
  (8574, 18, 18, null, 'Ausbau von Hochwasserschutzanlagen und Renaturierung von Uferbereichen.', '{1805}', 7942, 2, 3, null, 'Rückhalteräume und Auen dämpfen Hochwasserscheitel nachweislich, der Bund fördert Hochwasserschutz bereits mit. Dagegen: Deiche verlagern Risiken teils flussabwärts und ändern das Bauen in Überschwemmungsgebieten nicht.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=77', 'https://www.umweltbundesamt.de/hochwasser-durch-renaturierung-entschaerfen', 'belegt', '2026-10-07', false, true, 'blind'),
  (8575, 18, 18, null, 'Datengestützte Hitzestrategie mit Hitzeaktionsplänen und Förderprogrammen, gemeinsam mit den Ländern.', '{1802}', null, 2, 2, null, 'Hitzeschutzpläne gingen in 14 europäischen Ländern mit rund 25 % weniger hitzebedingten Todesfällen einher. Dagegen: Zusage ohne Mittel und Ziele; Umsetzung liegt bei Ländern und Kommunen, der Bund kann nur fördern und koordinieren.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=129', 'https://www.cmcc.it/article/heat-prevention-plans-help-save-lives', 'belegt', '2026-10-07', false, true, 'blind'),
  (8576, 18, 18, null, 'Stärkere Förderung von Projekten zur Senkung innerstädtischer Temperaturen, etwa Begrünung.', '{1803}', 7940, 2, 3, null, 'Parks und Bäume kühlen nachweislich (große Parks 1 bis 2 °C im Umfeld); der Bund fördert Städtebau bereits. Dagegen: Wirkung bleibt lokal und hängt von Umsetzung in den Kommunen ab.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=129', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6458494/', 'belegt', '2026-10-07', false, true, 'blind'),
  (8577, 18, 18, null, 'Europäischen Emissionshandel (ETS-2) wie geplant 2027 ausweiten.', '{1801,1802}', null, 1, 1, null, 'CO2-Preise senken Emissionen nachweislich, auf Hitze wirkt das aber nur gering und verzögert. Der Start 2027 ist durch EU-Recht (2026) bereits auf 2028 verschoben; Deutschland kann das nicht allein ändern.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=60', 'https://www.roedl.com/insights/ets-2-verzoegert-klimakosten-bleiben-warum-sie-nicht-auf-die-politik-warten-sollten-2/', 'belegt', '2026-10-07', false, true, 'blind'),
  (8578, 18, 18, null, 'Fossile Energieträger in Industrieanlagen bis 2035 befristen; neue Anlagen mit Strom oder Wasserstoff.', '{1801,1802}', null, 1, 1, null, 'Eine Frist für fossile Energie in der Industrie würde Emissionen senken. Dagegen: Laut UBA ist die Umstellung der Prozesswärme bis 2045 machbar, 2035 ist sehr knapp, Wasserstoff und Strom fehlen, Bestandsschutz wirft Rechtsfragen auf; Wirkung auf Hitze gering.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=61', 'https://www.umweltbundesamt.de/themen/industrielle-prozesswaerme-kann-bis-2045-co2', 'offen', '2026-10-07', false, true, 'blind'),
  (8579, 18, 18, null, 'CCS für unvermeidbare Industrieemissionen.', '{1801,1802}', 7935, 1, 3, null, 'Seit Ende 2025 ist kommerzielles CCS rechtlich möglich; es kann schwer vermeidbare Industrieemissionen senken. Dagegen: Infrastruktur braucht 7 bis 10 Jahre, Kosten und Umfang sind unsicher; Wirkung auf Hitze gering.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=62', 'https://www.bundesregierung.de/breg-de/aktuelles/speicherung-von-kohlendioxid-2376946', 'gemischt', '2026-10-07', false, true, 'blind'),
  (8580, 18, 18, null, 'Nationales Sanierungsprogramm für klimaneutrales Bauen und Sanieren öffentlicher Gebäude.', '{1801,1802}', null, 1, 2, null, 'Sanierung öffentlicher Gebäude senkt Energiebedarf und Emissionen (dena: rund 120 Mrd. Euro bis 2045 nötig, meist kommunale Gebäude). Auf Hitze in Deutschland wirkt das nur als kleiner Beitrag zum globalen Klimaschutz; Finanzierung offen.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=96', 'https://www.pv-magazine.de/?p=23862', 'belegt', '2026-10-07', false, true, 'blind'),
  (8581, 18, 18, null, 'Renaturierung und Wiedervernässung von Mooren massiv ausbauen.', '{1801,1802}', null, 1, 2, null, 'Entwässerte Moore verursachen laut UBA rund 7,5 % der deutschen Emissionen, Wiedervernässung senkt sie deutlich. Dagegen: Flächen meist privat, Wasser fehlt teils, Umsetzung über Länder; auf Hitze wirkt nationaler Klimaschutz nur gering und langfristig.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=79', 'https://www.umweltbundesamt.de/node/102188', 'belegt', '2026-10-07', false, true, 'blind'),
  (8582, 18, 18, null, 'Subventionen für fossile Energieträger in der Industrie vollständig abbauen.', '{1801,1802}', null, 1, 2, null, 'Steuervergünstigungen für fossile Energie mindern Sparanreize, ihr Abbau stützt Klimaschutz und entlastet den Haushalt. Dagegen: Abwanderungsrisiko energieintensiver Industrie, Wirkung kaum beziffert; auf Hitze in Deutschland nur geringer, verzögerter Effekt.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=62', 'https://www.umweltbundesamt.de/themen/umweltschaedliche-subventionen-klettern-auf-ueber', 'gemischt', '2026-10-07', false, true, 'blind');

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (7932, 18),
  (7933, 18),
  (7934, 18),
  (7935, 18),
  (7936, 18),
  (7937, 18),
  (7938, 18),
  (7939, 18),
  (7940, 18),
  (7941, 18),
  (7942, 18),
  (7943, 18),
  (7944, 18),
  (7951, 18),
  (7954, 18),
  (7956, 18),
  (7960, 18),
  (7964, 18),
  (7965, 18),
  (7966, 18),
  (7967, 18),
  (7968, 18),
  (7972, 18),
  (7973, 18),
  (7975, 18),
  (7979, 18),
  (7980, 18),
  (7981, 18),
  (7984, 18),
  (7985, 18),
  (7987, 18),
  (8575, 18),
  (8577, 18),
  (8578, 18),
  (8580, 18),
  (8581, 18),
  (8582, 18);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (18, 11, null, 'massnahmen', null, '2026-10-04', true, '{1801,1802,1803,1804,1805,1806}'),
  (18, 12, null, 'massnahmen', null, '2026-10-04', true, '{1801,1802,1803,1804,1805,1806}'),
  (18, 13, null, 'massnahmen', null, '2026-10-04', true, '{1801,1802,1803,1804,1805,1806}'),
  (18, 14, null, 'massnahmen', null, '2026-10-04', true, '{1801,1802,1803,1804,1805,1806}'),
  (18, 15, null, 'massnahmen', null, '2026-10-04', true, '{1801,1802,1803,1804,1805,1806}'),
  (18, 16, null, 'massnahmen', null, '2026-10-04', true, '{1801,1802,1803,1804,1805,1806}'),
  (18, 17, null, 'massnahmen', null, '2026-10-04', true, '{1801,1802,1803,1804,1805,1806}'),
  (18, 18, null, 'massnahmen', null, '2026-10-07', true, '{1801,1802,1803,1804,1805,1806}');

commit;
